version: '3.9'

services:
  frontend:
    build:
      context: ./flutter_project
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - API_HOST=http://backend:8080   # nombre del servicio backend

  backend:
    build:
      context: ./deu-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
