spring.application.name=deu
# URL de conexi�n para la base de datos H2
spring.datasource.url=jdbc:h2:mem:deuDB

# Usuario y contrase�a para la base de datos
spring.datasource.username=sa
spring.datasource.password=pass

# Driver de la base de datos H2
spring.datasource.driver-class-name=org.h2.Driver

# Dialecto de Hibernate para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Configuraci�n para crear y actualizar las tablas autom�ticamente
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true

# Consola de H2 habilitada
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Activar Swagger UI
springdoc.api-docs.enabled=true
jwt.secret = 9a0cac7ccbdab96c6bfa64e5ea714167866e4c1a1c8a63b7a52a5c8b01b8e757
jwt.accessTokenExpiration = 10000